preprocess:
    save: true
    use_cache: true

dataset:
    name: chess
    data_dir: data/chess
    edge_list_file: out.chess
    walks_file: walks.json
    tokenizer_file: tokenizer.json
    encoded_file: encoded.pt
    edge_split_file: splits.json
    meta_file: meta.json
    max_walk_length: 20
    mask_prob: 0.5
    ignore_index: -100
    num_walks: 1000000
    train_ratio: 0.8
    val_ratio: 0.1
    test_ratio: 0.1

model:
    embedding_dim: 128
    hidden_dim: 256
    dropout: 0.1
    nhead: 4
    nlayers: 2

training:
    batch_size: 64
    epochs: 10
    lr: 1e-3
    weight_decay: 1e-5
    early_stopping_patience: 10
    log_dir: logs/
    exp_name: walk_to_paint_experiment
    checkpoint_dir: checkpoints/
    resume_from_checkpoint: null
    eval_only: false
    use_cuda: true
