preprocess:
    save: false
    use_cache: false

dataset:
    name: bitcoin-alpha-binary
    data_dir: data/bitcoin-alpha-binary
    edge_list_file: soc-sign-bitcoinalpha-binary.csv
    walks_file: walks.json
    tokenizer_file: tokenizer.json
    encoded_file: encoded.pt
    edge_split_file: splits.json
    meta_file: meta.json
    max_walk_length: 40
    num_walks: 1000000
    train_ratio: 0.7
    mask_ratio: 0.1
    val_ratio: 0.1

model:
    embedding_dim: 8
    hidden_dim: 8
    dropout: 0.2
    nhead: 4
    nlayers: 2

training:
    batch_size: 128
    epochs: 50
    lr: 1e-3
    weight_decay: 1e-1
    early_stopping_patience: 10
    gradient_clip_val: 1.0
    use_weighted_loss: true
    log_dir: logs/
    exp_name: walk_to_paint_experiment
    checkpoint_dir: checkpoints/
    resume_from_checkpoint: null
    eval_only: false
    use_cuda: true
