preprocess:
    save: false
    use_cache: false

dataset:
    name: bitcoin-alpha-binary
    data_dir: data/bitcoin-alpha-binary
    edge_list_file: soc-sign-bitcoinalpha-binary.csv
    walks_file: walks.json
    tokenizer_file: tokenizer.json
    encoded_file: encoded.pt
    edge_split_file: splits.json
    meta_file: meta.json
    max_walk_length: 83
    num_walks: 219589
    train_ratio: 0.48
    mask_ratio: 0.32
    val_ratio: 0.1
    test_ratio: 0.1

model:
    embedding_dim: 32
    hidden_dim: 16
    dropout: 0.6207573207736868
    nhead: 8
    nlayers: 5

training:
    batch_size: 64
    epochs: 25
    lr: 0.0011990397793339518
    weight_decay: 0.0026821863636421073
    early_stopping_patience: 10
    gradient_clip_val: 0.5956847053697083
    use_weighted_loss: true
    log_dir: logs/
    exp_name: walk_to_paint_experiment
    checkpoint_dir: checkpoints/
    resume_from_checkpoint: null
    eval_only: false
    use_cuda: true
